baseURL = 'https://ramzeng.github.io/'
title = 'Tech'
languageCode = 'en'

theme = "paper"

# use disqus comments
# disqusShortname = 'YOUR_DISQUS_SHORTNAME'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[params]
    # linen, wheat, gray, light
    color = 'linen'

    # header social icons
    # twitter = ''
    github = 'ramzeng'
    # instagram = ''
    # linkedin = ''
    # mastodon = ''
    rss = true

    # home page profile
    avatar = 'https://avatars.githubusercontent.com/u/38133602'                 # gravatar email or image url
    name = '是然'
    bio = '应该有点逻辑。'

    # misc
    # disable highlight.js
    disableHLJS = true

    # show monochrome dark mode icon
    monoDarkIcon = true

    # e.g. 'https://cdn.v2ex.com/gravatar/'
    # gravatarCdn = ''

    # use graph comment (disqus alternative)
    # graphCommentId = "YOUR_GRAPH_COMMENT_ID"

    # enable KaTex math typesetting globally
    math = true
